stages:
  - deploy

deploy-site:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  variables:
    S3_BUCKET_URI: "s3://jonny-nginx-bucket"
    STATIC_SITE_FILE_PATH: "playground/nginx-autoscaling/public/index.html"
  script: 
    - aws s3 cp $STATIC_SITE_FILE_PATH s3://$S3_BUCKET_URI
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"
      when: always
